### PR TITLE
fix: Use fixed UniFFI branch to fix RustBuffer issues on iOS/Android [WPB-9007]

### PR DESCRIPTION
**Pull request by OtaK**

### CODE REVIEW

**Review by augustocdias — APPROVED** [review]

**Comment by OtaK** [comment]
Use: https://github.com/mozilla/uniffi-rs/commit/028f34b63352ccb8d8aeaf3506126f35e93ee113

**Comment by SimonThormeyer** [comment]
Can be closed as we have updated uniffi to 0.28 which includes this fix.

**Comment by SimonThormeyer** [comment]
Can be closed as we have updated uniffi to 0.28 which includes this fix.

**Comment by istankovic** [comment]
Since we moved to the uniffi version that has this fixed, we can close this now.

**Pull request closed without merging**
