### PR TITLE
chore: Release 0.6.1

### PR DESCRIPTION
**Pull request by typfel**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Release 0.6.1

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by OtaK — APPROVED** [review]

**Comment by typfel** [comment]
Hmm I see now that my handwritten release didn't get included in the change log.

**Comment by OtaK** [comment]
> Hmm I see now that my handwritten release notes didn't get included in the change log.

You need to write them in the tpl file; the md file is meant to never be edited by hand

**Review by beltram — APPROVED** [review]

**Comment by typfel** [comment]
```
expect(received).toMatch(expected)
[35](https://github.com/wireapp/core-crypto/actions/runs/4192714149/jobs/7268658956#step:10:36)

[36](https://github.com/wireapp/core-crypto/actions/runs/4192714149/jobs/7268658956#step:10:37)
    Expected substring: "0.6.0"
[37](https://github.com/wireapp/core-crypto/actions/runs/4192714149/jobs/7268658956#step:10:38)
    Received string:    "0.6.1"
[38](https://github.com/wireapp/core-crypto/actions/runs/4192714149/jobs/7268658956#step:10:39)

[39](https://github.com/wireapp/core-crypto/actions/runs/4192714149/jobs/7268658956#step:10:40)
      69 |   });
[40](https://github.com/wireapp/core-crypto/actions/runs/4192714149/jobs/7268658956#step:10:41)
      70 |
[41](https://github.com/wireapp/core-crypto/actions/runs/4192714149/jobs/7268658956#step:10:42)
    > 71 |   expect(version).toMatch("0.6.0");
[42](https://github.com/wireapp/core-crypto/actions/runs/4192714149/jobs/7268658956#step:10:43)
         |                   ^
[43](https://github.com/wireapp/core-crypto/actions/runs/4192714149/jobs/7268658956#step:10:44)
      72 |
[44](https://github.com/wireapp/core-crypto/actions/runs/4192714149/jobs/7268658956#step:10:45)
      73 |   await page.close();
[45](https://github.com/wireapp/core-crypto/actions/runs/4192714149/jobs/7268658956#step:10:46)
      74 |   await ctx.close();
[46](https://github.com/wireapp/core-crypto/actions/runs/4192714149/jobs/7268658956#step:10:47)

[47](https://github.com/wireapp/core-crypto/actions/runs/4192714149/jobs/7268658956#step:10:48)
      at Object.toMatch (test/CoreCrypto.test.js:71:19)
```

@OtaK do I need re-generate the WASM bindings?

**Comment by OtaK** [comment]
> ```
> expect(received).toMatch(expected)
> Expected substring: "0.6.0"
> Received string:    "0.6.1"
>   69 |   });
>   70 |
> > 71 |   expect(version).toMatch("0.6.0");
>      |                   ^
>   72 |
>   73 |   await page.close();
>   74 |   await ctx.close();
>   at Object.toMatch (test/CoreCrypto.test.js:71:19)
> ```
> 
> @OtaK do I need re-generate the WASM bindings?

No, just change the `expect(version).toMatch("0.6.0")` to `expect(version).toMatch("0.6.0")`

I'll make it automated at some point : D

**Pull request merged**
